### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by Insadem** [rhenrywarren/CrossoverFree#1]
I have a golang version made by myself, no dependencies. Will you publish it if I send it to you? It's ~2mb size for macos when compiled to arm

**Comment by rhenrywarren** [comment]
Yeah sure, send it to me at rhenrywarren@gmail.com, and I'll take a look at it, if i publish it I'll gibe you credit where it's due!

**Comment by rhenrywarren** [comment]
Still send me the program but this repo is shutting down per CodeWeavers DMCA Takedown Notice: Henry,

Per GitHub's Suggestion, I am asking you to remove all traces of your Repo to circumvent the licensing of our CrossOver product. I am not under the illusion that did not realize that you were doing anything wrong in your extensive efforts to circumvent our licensing (although posting this under your real name is a bold touch)

**Comment by rhenrywarren** [comment]
see you on the other side
